//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Name is Rrquired. ")]
        public string Name { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Position is Rrquired. ")]
        public string Position { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Style is Rrquired. ")]
        public string Style { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Age is Rrquired. ")]
        public string Age { get; set; }
    }
}
