//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is Rrquired. ")]
        public string FirstName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is Rrquired. ")]
        public string LastName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "User Name is Rrquired. ")]
        public string UserName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "password is Rrquired. ")]
        public string Password { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Age is Rrquired. ")]
        public int Age { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Emai id is Rrquired. ")]
        public string Email { get; set; }
    }
}
